### ISSUE TITLE
Prose.io is a tool for visual editing of markdown

### ISSUE THREAD

**Issue by drewrwilson** [18mr/documentation#11]
Love your documentation here. Thanks for sharing it on github!

After reading your list of resources, I thought may also be interested in [Prose.io[(http://prose.io/). It's a WYSIWYG editor for markdown on github. Maybe something that helps your campaigners write content in markdown to be used by Jekyll.

**Comment by catachresis** [comment]
There's some existing bug in Prose that made me deselect it as a tool and I don't remember off the top of my head what it is. I think it had something to do with metadata? This was a while ago and I remember reading that the developers of Prose were not super keen on fixing it because GitHub had added some in-browser editing functionality. I might loop back around to see if that _did_ get fixed...

**Comment by catachresis** [comment]
Looks like the bug may be fixed. I might keep folks using this workflow though, since the new GitHub GUI updates make a lot of these multistep processes incredibly simple!
